export const actionItems = [
  {id: 1,
    header: 'Upload signature',
    note: "You're required to upload signatures for members of the company for the CAC Form",
    deadline: '12/09/2024',
    label: 'Upload',
  },
  {id: 2,
    header: 'Renew annual year returns',
    note: "You're required to upload signatures for members of the company for the CAC Form",
    deadline: '12/09/2024',
    label: 'Upload',
  },
  {id: 3,
    header: 'Make Payment',
    note: "You're required to upload signatures for members of the company for the CAC Form",
    deadline: '12/09/2024',
    label: 'Upload',
  },
  {id: 4,
    header: 'Make Payment',
    note: "You're required to upload signatures for members of the company for the CAC Form",
    deadline: '12/09/2024',
    label: 'Upload',
  },
];
